### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by geoidesic** [Codaxis/cakephp-parsley-helper#4]
Maybe this seems like a silly question but how do I install this into my code base?
Obviously I can copy the helper file into Views/Helpers... but what about the library file and the trait file?

I'm getting errors like this:
Missing Plugin
Error: The application is trying to load a file from the ParsleyHelper plugin
Error: Make sure your plugin ParsleyHelper is in the app/Plugin directory and was loaded

--- and ---

Plugin ParsleyHelper could not be found

**Comment by augusto-cdxs** [comment]
Hello geoidesic. First of all I have to warn you that this plugin is not maintained anymore.
To make the helper work you have to copy the entire code as a normal cakephp plugin in your app/Plugin folder, name it "ParsleyHelper", and follow the steps listed under "Basic usage". The helper will not work separatedly.
Trait usage is advised only when you want to make use of your custom helper and have already overriden a Vendor helper as well.
